### ISSUE TITLE
The SEL plugin requires modifications

### ISSUE THREAD

**Issue by Uffel3** [transpower-nz/open-scd#12]
The SEL plugin is great to automatically subscribe three phase current and voltage SV from a merging unit in the `Subscriber` Editor. However, voltage inputs `VAZ` and `VBZ` are single phase voltages from different MU's. At the moment, I have to 

1. connect MU1 to `VAZ` which automatically maps `VCZ` and `VCZ` as well.
2. Unmap `VBZ` and `VCZ`
3. connect MU2 to `VBZ` which automatically maps `VCZ`
4. Unmap `VCZ`
5. open the `Supervision` editor and re-map LSVS to the correct publishers. 

We can either improve the SEL plugin, or I need to write detailed instructions on how to handle SEL-411L-2 relay SV subscriptions. Thoughts?

**Comment by danyill** [comment]
You can remove the automatic modifications by either disabling the specific plugin or:

![image](https://github.com/transpower-nz/open-scd/assets/674783/c476d3db-b404-45e7-b703-900af2e2ecf7)

Is this sufficient?

**Comment by Uffel3** [comment]
Ok, I accept. The Prot 1 Engineering guide needs a bit more explanation/guidance in how to manage the SEL-411L-2.
