### ISSUE TITLE
Manual change of multicast MAC address does not occur in all parts

### ISSUE THREAD

**Issue by Uffel3** [transpower-nz/open-scd#16]
I use the `TP Multicast Naming` editor to allocate new mac addresses to IEDs. Then I went to the `Publisher` Editor and manually changed the MAC address of all GSE and SV. When you open the attached SCD file, then you will see that we still have 

* 01-0C-CD-01-00-03 (SEL-411L-2)
* 01-0C-CD-01-00-04 (SEL-411L-2)
* 01-0C-CD-01-00-05 (SEL-411L-2)

Why is that so? 

![image](https://github.com/transpower-nz/open-scd/assets/153496067/142cc116-8644-423d-b0bf-dee97c9b4d6e)

[PCS-221S Component Testing - Copy.zip](https://github.com/transpower-nz/open-scd/files/14626495/PCS-221S.Component.Testing.-.Copy.zip)

**Comment by danyill** [comment]
This was not an issue - lack of understanding of SCD files.
