### ISSUE TITLE
TP Multicast naming gets SEL-411L-2 Half CB GCB incorrect

### ISSUE THREAD

**Issue by Uffel3** [transpower-nz/open-scd#2]
When I try to use OpenSCD to automatically update all addresses, it does not address the SEL-411L-2 `HalfCB` Goose Control Block properly:

1. VLAN 1001 is reserved for SV. The VLAN is must communicate between different busbars (The line protection sends signals to the opposite side of the diameter).
2. VLAN Priority shall be 6 since it includes trip signals.
3. The `min time` shall be 4 ms.

![image](https://github.com/transpower-nz/open-scd/assets/153496067/56402b9a-8e4e-4166-af57-aaade0e4b0d7)

**Comment by danyill** [comment]
Thanks for filing, the TP Multicast Naming needs refactoring and tests added and we'll address this then, soon (hopefully).
