### ISSUE TITLE
Communication Explorer incorrectly list publishers as subscribers in focus mode

### ISSUE THREAD

**Issue by aus-betz** [transpower-nz/open-scd#24]
When an IED is selected in focus mode, subscribed messages have the publisher listed under the 'Subscribers' section as shown in the example below. The heading should either be updated to publisher (probably the more useful option), or alternatively list all other subscribers to the message.

![image](https://github.com/user-attachments/assets/eaa14a9a-db4d-49ae-afb3-9641a9ff6c59)

**Comment by aus-betz** [comment]
On second thought, perhaps 'Publisher' should be added in the same section as the Label & Message Type, and then a compressible list of subscribers be included in the current 'Subscribers' section. This would provide all relevant info in a concise manner, and would be of use during commissioning when checking what other devices would be affected by altering test quality or similar attributes.

**Comment by danyill** [comment]
A fix is on the way :tada:

**Comment by danyill** [comment]
I think this one is now fixed upstream, please test and re-open if necessary.
