### ISSUE TITLE
IED Editor can't handle changing only the IED description

### ISSUE THREAD

**Issue by aus-betz** [transpower-nz/open-scd#25]
When attempting to edit the description of the IED (crucial for SIPROTEC 5 devices to avoid duplicate device names in DIGSI 5), the dialog box does not accept modification of only the description as it flags the name as already in use.

![image](https://github.com/user-attachments/assets/ebb6c76e-54b1-41c0-916d-ead1b11b9aab)

Workaround is to use the XML editor option in the dialogue box to manually make the change.

**Comment by danyill** [comment]
I believe this is now resolved, please check and re-open if it is not fixed.

You can also access the wizard from the SLD Designer now.
