### ISSUE TITLE
Improvement to Stencil Editor - Deselect entire rows (and possibly columns)

### ISSUE THREAD

**Issue by aus-betz** [transpower-nz/open-scd#26]
When creating stencils, it would be nice to be able to deselect entire rows in the stencil editor. Generally, I am creating one stencil per GOOSE application, and so I am looking to select only one GOOSE message from the SCD and connecting the subscribers to that source.

This will be different when I set up 220kV bay level stencils, but for 33kV or for busbars it would be quite useful. Given this is something done once (hopefully!) during development, it isn't a critical issue, just a nice UX improvement!

![image](https://github.com/user-attachments/assets/800a9eda-9e84-4a50-b815-a52f331470a5)

**Comment by danyill** [comment]
That's a good idea, let's do that 👍

**Comment by danyill** [comment]
I did some refactoring and had a go at this. I have deployed - please test

**Comment by aus-betz** [comment]
New functionality works quite well. Pretty much exactly as I envisioned it, and worked well for a new temporary stencil I created today.
