### ISSUE TITLE
Update Communication Explorer to 0.0.31

### ISSUE THREAD

**Issue by jarradraumati** [transpower-nz/open-scd#27]
`0.0.31` dramatically improves the performance of this plugin, and eliminates the irksome accidental click of the editor menu and long wait time.
See https://github.com/sprinteins/oscd-plugins/pull/51

**Comment by danyill** [comment]
Still takes about 20-30 s for me in our subsystem test SCD file but I've updated the distribution, thanks for the hint.

**Comment by danyill** [comment]
Hmmm, but it is much faster in https://openscd.sprinteins.com/ I guess the release builds gh-pages and it's not a rolling release so we need to wait a little.

**Comment by danyill** [comment]
I guess it's 0.0.32 we're waiting for. I continue to tweak Tamas.

**Comment by danyill** [comment]
Actually 0.0.31 is fine and I just needed to change the plugin - it's now nice and fast.

**Comment by danyill** [comment]
Resolved in d5aabd952d93cf6475d7592c2e1660c6e1a98843
