### ISSUE TITLE
Cannot select busbar in multicast naming function

### ISSUE THREAD

**Issue by Uffel3** [transpower-nz/open-scd#3]
I created an SCD file with a single PCS-221S and a single SEL-411L-2 relay (see zip file). I did the SLD modifications as per D Chen's instructions. 

However, the multicast page does not show devices allocated to Bus A. 

![image](https://github.com/transpower-nz/open-scd/assets/153496067/24292451-b9b7-43ca-92f5-23a262468e88)

[For Daniel.zip](https://github.com/transpower-nz/open-scd/files/14490787/For.Daniel.zip)

**Comment by Uffel3** [comment]
I have added a second busbar with a single IED.  Here is the result. XAT_262_P1 should be on BusB, and the rest on BusA. I am sure I made a mistake.

![image](https://github.com/transpower-nz/open-scd/assets/153496067/e4710204-1e56-4b4f-a50b-a962b25f68b9)

![image](https://github.com/transpower-nz/open-scd/assets/153496067/a6b6230f-487d-4bbc-bbe7-33793b933fcb)

**Comment by danyill** [comment]
Hmmm the file you provide appears only to show Bus A with IEDs.

![image](https://github.com/transpower-nz/open-scd/assets/674783/8eb67d7a-4941-4651-a952-8db5cfe40090)

Additionally, it is not showing the Function structure I expect:

![image](https://github.com/transpower-nz/open-scd/assets/674783/ccba7649-9c3b-4b0c-8e20-f9ca143f9fa4)

The LNodes should be created under a Function called `BusPhysConnection` which is shown in the instructions.

After I make these changes to your file it seems to work.

![image](https://github.com/transpower-nz/open-scd/assets/674783/37a53d03-fbc4-4b7d-a0b6-386955d699d6)

![image](https://github.com/transpower-nz/open-scd/assets/674783/166073ef-06ba-4735-8a23-0769d37ffaa3)

>I am sure I made a mistake.

Me too :wink: 

Here's my result:

[Maik Test.scd.zip](https://github.com/transpower-nz/open-scd/files/14491200/Maik.Test.scd.zip)

If you agree, please close the issue.

**Comment by Uffel3** [comment]
Yes, I made a mistake 😢 I did that procedure three times today, but then missed that crucial step.

The German say: Wer lesen kann, ist klar im Vorteil! (translated: it is a clear advantage if you can read!)

Case closed.
