### ISSUE TITLE
When adding Data objects the pop up says data attributes

### ISSUE THREAD

**Issue by IanYoung77** [transpower-nz/open-scd#31]
Small issue but can be confusing
![image](https://github.com/user-attachments/assets/110cb488-2077-4aa5-8f53-ddc247af8f0a)

**Comment by danyill** [comment]
I believe this is fixed now.

To refresh, suggest pressing Ctrl + F5.

Thanks for reporting, please re-open if it is not fixed.

**Comment by IanYoung77** [comment]
All good. Thanks
