### ISSUE TITLE
Rename dialog in SLD Designer wipes all IEDName entries from GSEControl blocks

### ISSUE THREAD

**Issue by aus-betz** [transpower-nz/open-scd#36]
When changing only the description field in SLD Designer (i.e. leaving the IEDName field unchanged), the GSEControl blocks referencing that IEDname are wiped:

`<GSEControl name="BT_Interlocks" datSet="BT_Interlocks" confRev="1" type="GOOSE" appID="Interlocks from Bus Tie DIS Panel">
	<IEDName apRef="E" />
	<IEDName apRef="E">CBWM1PNL13EPR01</IEDName>
</GSEControl>`

In the example above, the first IED had the description changed in SLD Designer, whereas CBWM1PNL13EPR01 was not modified at all.

**Comment by aus-betz** [comment]
Actually, with a little further testing, it appears that any edits in the Rename IED dialog in SLD Designer wipes the IEDName in the GSEControls...

**Comment by danyill** [comment]
Both the SLD Designer and the Rename IEDs are using the same scl-lib function. It may be I haven't updated these plugins correctly - I'll take a look

**Comment by danyill** [comment]
I don't see this behaviour with the Rename IEDs plugin.
I do see some problem with the Designer plugin but only on supervisions not IEDName elements. But I think something is going wrong as the edit history shows:

![image](https://github.com/user-attachments/assets/fe6c3beb-347f-4f53-ab00-7d79969829ed)

Still investigating.

**Comment by danyill** [comment]
Oh actually it's the same bug but it's now affecting scl-wizarding. The wizards also depend on scl-lib and we've fixed up the bug in scl-lib but not updated scl-wizarding

**Comment by danyill** [comment]
I've filed an issue, hopefully upstream can do an overnight release - sorry for the trouble 

https://github.com/OpenEnergyTools/scl-wizarding/issues/13

**Comment by danyill** [comment]
This is now fixed, sorry for the delay - please test and reopen if required.
