### ISSUE TITLE
Publisher page does not update when changes are made

### ISSUE THREAD

**Issue by Uffel3** [transpower-nz/open-scd#4]
I wanted to manually change MAC addersses of each GSE.  Once I save my newly selected MAC address, and select a different GSE in the list, the MAC address does not change (but other parameters do). You need to move to a different editor tab (e.g. TP Multicast naming) to see that the MAC address has been updated. When you go back to the `Publisher` editor, the MAC address is updated.

![image](https://github.com/transpower-nz/open-scd/assets/153496067/73475ea0-5c59-48f1-9830-c38330a6eaf9)

**Comment by danyill** [comment]
@JakobVogelsang has fixed this in the plugin and I have tested and redeployed the distribution. Thanks Jakob! :+1:
